### ISSUE TITLE
mobile/iphone font size too large

### ISSUE THREAD

**Issue by aseelye** [IvarK/IvarK.github.io#11]
There seems to be an update in the last day where the type size is large enough that one can't see the cost of an upgrade beyond the word "Cost:"
![img_3272](https://user-images.githubusercontent.com/5467946/29743079-4b2db524-8a3f-11e7-9643-ef22c7dd72fe.PNG)
![img_3273](https://user-images.githubusercontent.com/5467946/29743078-4b2c80c8-8a3f-11e7-8f1d-f6ee9b853226.PNG)

**Comment by omsi6** [comment]
Cannot reproduce in the current build. Please reopen if you still experience the issue.
