### ISSUE TITLE
'Zero Deaths' Achievement is impossible after 500 IP purchase

### ISSUE THREAD

**Issue by RayMarDesign** [IvarK/IvarK.github.io#176]
The 'You start with 8th dimension and a Galaxy' 500 IP purchase makes it impossible to get the 'Zero Deaths' achievement.

While it is still possible to get it within a challenge, I don't believe the intent of this achievement is to get infinity with _only_ dimensions 1-4.

**Comment by omsi6** [comment]
That is the intent.
