### ISSUE TITLE
Automatic Dimboosts - Off by one error

### ISSUE THREAD

**Issue by mart0258** [IvarK/IvarK.github.io#184]
https://github.com/IvarK/IvarK.github.io/blob/b5d736110b5f6be8cfd29ec493c7cdd102435ada/javascripts/game.js#L6403

Function maxBuyDimBoosts() has an off-by-one error. First, it adjusts players.resets directly to perform these soft resets, and does so to the correct value. It then calls softReset(0), which autoconverts the parameter to 1, triggering an additional dim boost. 

Easiest fix is calling softReset(r), rather than adjusting player.resets.

**Comment by 1234abcdcba4321** [comment]
resolved with my update

**Comment by omsi6** [comment]
as noted above
