### ISSUE TITLE
Weird stuff with doing Dimensional Boosts Challenge late in the game

### ISSUE THREAD

**Issue by dan-simon** [IvarK/IvarK.github.io#212]
If you do Dimensional Boosts Challenge with enough eternities:
* Due to not taking account of bulk correctly in Dimensional Boosts Challenge, the Dimensional Shift button breaks (the game enters an infinite loop due to trying to reset infinitely many times).
* Due to not taking account of Dimensional Boosts Challenge at all, max buying galaxies breaks (it doesn't buy any since there are no eighth dimensions to buy them with).
* if the above two issues were fixed, you could get tons of galaxies if you were in EC7 with some first ID, since first ID will produce lots of seventh dimensions which will produce lots of sixth dimensions. It's as if there were a ninth dimension.

(Should I sign up for the discord and post these there? The issues section looks rather empty, and I don't want to create a lot of noise.)

**Comment by omsi6** [comment]
Using github to report bugs is totally fine, however if it's a serious gameplay affecting issue like the C8 one, I would recommend PMing me or Hevipelle on discord so we can see it right away.

**Comment by omsi6** [comment]
A PR has been made with fixes to these issues. Also, EC7 will no longer do anything in C10 because it produces 7th dims, and C10 states there and only 6 dimensions.
