### ISSUE TITLE
Production chart should be smoother

### ISSUE THREAD

**Issue by nondebug** [IvarK/IvarK.github.io#229]
In addData you're changing the plotted values based on whether or not the player has notation set to Logarithm mode. But the non-Logarithm values are wrong and make the chart look wavy with a visible transition at each new exponent.

https://github.com/IvarK/IvarK.github.io/blob/master/javascripts/game.js#L524

**Comment by omsi6** [comment]
How are they incorrect exactly? Non-logarithmic growth speeds as it approaches a full integer. For example, 1e1000 + 10% = 1.1e1000 (so adding an effective 0.1e1000) whereas 9e1000 + 10% = 9.90e1000 (adding an effective 0.9e1000). This is just a natural consequence of how the numbers work. Unless I'm missing something, and there's a very good chance I am.

**Comment by nondebug** [comment]
The main problem is that the chart is always semi-log (linear on the time axis, logarithmic on the antimatter axis) regardless of the player's notation option, so the behavior shouldn't depend on that option anyway. The chart actually looks different based on the notation you've picked which IMO is a bug.

Plotting it as (exponent + 0.1 * mantissa) is incorrect because on a log scale larger mantissa values are plotted closer together than smaller values. You can see it on [this semi-log graph paper](http://www.med.harvard.edu/jpnm/physics/office/graph_paper/semilog/semilog_5.gif), the delta for 0.0 to 0.1 is much larger than 0.9 to 1.0 within each decade. Ignoring this is what makes gives the plot ripples at each exponent.

**Comment by omsi6** [comment]
That's a very reasonable point. Resolved in commit https://github.com/IvarK/IvarK.github.io/commit/c3e8d18c1e8bd0530befed5396db1108c0e052b7.
