### ISSUE TITLE
Free boost on reset, and "One for each dimension" not taken account of correctly

### ISSUE THREAD

**Issue by dan-simon** [IvarK/IvarK.github.io#231]
I'm in the first infinity and noticed some issues with my multipliers. For one thing, when I got my first galaxy, my first dimension multiplier is 3x, not 1.5x like it should be (from achievements). This seems to be due to the game determining dimension multipliers after galaxy or crunch with one more reset than it should (first dimension multiplier is (dimension boost power)^(resets + 1), not (dimension boost power)^resets).

Also , after my second galaxy I noticed that most of my dimension multipliers were a bit lower than they should be; second dimension multiplier was 1.4x, not 1.5x. This seems to be due to the line
```
if (player.achievements.includes("r35")) mult = mult.times(Math.pow(player.totalTimePlayed / (600*60*48), 0.05));
```
which gives the "One for each dimension" bonus. However, for a long time "One for each dimension" has been r76, not r35 (r35 is "Don't you dare sleep"). Since most people get "Don't you dare sleep" rather early, this means that production will be a little lower before eight days have passed.

Neither of these issues is really that big of a deal, but both seem fairly easy to fix and so I'll probably make a PR.

**Comment by omsi6** [comment]
Fixed (by you) in 0fe9e01c16088d9e503d68a981140da75a919d36.
