### ISSUE TITLE
qc4 meta dim boost bug and quark adding causes infinity bug

### ISSUE THREAD

**Issue by HalitZiyaKARTAL** [IvarK/IvarK.github.io#254]

**Comment by omsi6** [comment]
Hi Halit, you're reporting an issue for a modified version of the game, which I unfortunately cannot help you with. You can find a link [here](https://github.com/aarextiaokhiao/IvarK.github.io/) to the github repository for the modified version you're talking about.

**Comment by HalitZiyaKARTAL** [comment]
thanks :)

Jane Doe <notifications@github.com>, 7 Ağu 2019 Çar, 07:05 tarihinde şunu
yazdı:
