### ISSUE TITLE
[Aarex Mod]Offline simulation bug+Don't show offline progress

### ISSUE THREAD

**Issue by 1e1000000** [IvarK/IvarK.github.io#260]
I playing antimatter dimensions aarex modifier.
I playing to quantum challenge 6,tied 2 days.

I offline with 0 second eternity,after turn on matter increase to very huge,but no fail popup.
as I manually offline back,offline progress popup disappear.

**Comment by omsi6** [comment]
Sorry, but this is not the correct repo for this issue. You're looking for [Aarex's](https://github.com/aarextiaokhiao/IvarK.github.io) repo, as he is the creator of the mod that you're playing.
