### ISSUE TITLE
909: Dimension not Found uses wrong formula

### ISSUE THREAD

**Issue by exi** [IvarK/IvarK.github.io#268]
The code that checks for the achievement is:
```js
if (player.firstAmount == 1 && player.resets == 0 && player.galaxies == 0 && player.currentChallenge == "challenge12") giveAchievement("ERROR 909: Dimension not found")
```

However I think it should be "player.firstBought" instead of "player.firstAmount".
With the current constraint, it would require the player to go to infinity with just a single first dimension and not buying any other dimension because they would increase "player.firstAmount".

**Comment by aarextiaokhiao** [comment]
I will fix that.

**Comment by IvarK** [comment]
Infinity resets dimensions, so you can't get it that way. Furthermore if it's firstBought, then you could buy other dimensions, as second dimensions doesn't increase firstBought. The achievement is specifically "With only one first dimension", not "With just 1 bought first dimension".

**Comment by exi** [comment]
@IvarK Thanks for the clarification. Then this is mostly a description thing because me and some friends of mine all misunderstood the description.
Maybe we could explicitly state that this means with only buying one first dimension and no other.

**Comment by IvarK** [comment]
The description states "Get to Infinity with only a single first dimension...". If you have second dimensions, they produce first dimensions, thus you no longer have only a single first dimension. I think it's pretty straight forward.

**Comment by exi** [comment]
Fair enough, I'm also fine with closing this and accepting that a couple of people just did not understand it right away.  We have the explanation we needed :-)
