### ISSUE TITLE
Infinity break upgrade ignoring another upgrade

### ISSUE THREAD

**Issue by hugojmaia** [IvarK/IvarK.github.io#290]
Infinity break's "Passively generate Infinites based on your fastest Infinity" ignores Infinity's "Multiply Infinity from all sources by 2x"
![image](https://user-images.githubusercontent.com/8614893/219948346-91e89042-a2c8-458f-87c3-9b888ccaa836.png)
![image](https://user-images.githubusercontent.com/8614893/219948365-e51180d1-f8c4-44b0-ae08-3607ee6de590.png)
![image](https://user-images.githubusercontent.com/8614893/219948380-dca68e3d-1d37-4a1f-934b-53d825b4ce74.png)
As you can see on the image, all infinity sources multiplied by 128, fastest infinity 101ms, passive generation at 1 infinity every 202ms, which makes it a near worthless upgrade for the 2e7 infinity it cost at this stage of the game.
If the multiplier applied it'd increase from 297 infinity/minute to 3.8e4 infinity/minute, making it around 40% of my current infinity/minute.

**Comment by hugojmaia** [comment]
For comparison, the passive upgrade from the first tab:
![image](https://user-images.githubusercontent.com/8614893/219948813-ebbe11d6-32e4-400a-a91a-1a989989a78c.png)
At around 7.6e3 Infinity/minute.

**Comment by omsi6** [comment]
The first upgrade generates "infinities". the second upgrade generates infinity points. these are two different things. an infinity is something you get 1 of every time you big crunch. infinity points are variable and multiplied by other things, such as am after breaking infinity.
