### ISSUE TITLE
Javascript error on mobile

### ISSUE THREAD

**Issue by GrueStick** [IvarK/IvarK.github.io#65]
http://ivark.github.io/javascripts/game.js:80
Uncaught SyntaxError: Unexpected token >
`var c_value = escape(btoa(JSON.stringify(value, (k, v) => (v === Infinity) ? "Infinity" : v))) +`
![image](https://user-images.githubusercontent.com/31457874/29992410-755f5d10-8f4f-11e7-94dd-4062dafc9e65.png)

Seems to be a lack of support for JavaScript's arrow notation.  Ideally we should use a transpiler, however we can rewrite functions using the older notation as a quick fix.  For example:

```
function(k, v) {
    return (v === Infinity) ? "Infinity" : v;
}
```

**Comment by CatsAreFluffy** [comment]
Browsers aren't universally ES6 compatible?

**Comment by omsi6** [comment]
This has been fixed in an update at some point.
