### ISSUE TITLE
Game died

### ISSUE THREAD

**Issue by wetfart99** [IvarK/IvarK.github.io#7]
The game gets to this point then stops responding to any clicks other than changing to options or statistics.

![delete](https://cloud.githubusercontent.com/assets/24817602/21534146/31238b24-cd28-11e6-96cf-9e4110a2e692.png)

**Comment by wetfart99** [comment]
I refreshed the page and now I can't even get the Options and Statistics buttons to work.

**Comment by wetfart99** [comment]
eyJtb25leSI6bnVsbCwidGlja1NwZWVkQ29zdCI6MCwidGlja3NwZWVkIjoxLjVlLTMyMywiZmlyc3RDb3N0IjoxZSszMDQsInNlY29uZENvc3QiOjkuOTk5OTk5OTk5OTk5OTk5ZSszMDUsInRoaXJkQ29zdCI6OS45OTk5OTk5OTk5OTk5OTdlKzMwMywiZm91cnRoQ29zdCI6OS45OTk5OTk5OTk5OTk5OTdlKzMwNSwiZmlmdGhDb3N0IjoxLjAwMDAwMDAwMDAwMDAwMDNlKzMwNSwic2l4dGhDb3N0Ijo5Ljk5OTk5OTk5OTk5OTk5N2UrMzAyLCJzZXZlbnRoQ29zdCI6MS4wMDAwMDAwMDAwMDAwMDAzZSszMDYsImVpZ2h0Q29zdCI6bnVsbCwiZmlyc3RBbW91bnQiOm51bGwsInNlY29uZEFtb3VudCI6bnVsbCwidGhpcmRBbW91bnQiOm51bGwsImZvdXJ0aEFtb3VudCI6bnVsbCwiZmlyc3RCb3VnaHQiOjAsInNlY29uZEJvdWdodCI6MCwidGhpcmRCb3VnaHQiOjAsImZvdXJ0aEJvdWdodCI6MCwiZmlmdGhBbW91bnQiOm51bGwsInNpeHRoQW1vdW50IjpudWxsLCJzZXZlbnRoQW1vdW50IjpudWxsLCJlaWdodEFtb3VudCI6MTkwLCJmaWZ0aEJvdWdodCI6MCwic2l4dGhCb3VnaHQiOjAsInNldmVudGhCb3VnaHQiOjAsImVpZ2h0Qm91Z2h0IjowLCJmaXJzdFBvdyI6MS42NjE1MzQ5OTQ3MzExNDVlKzM1LCJzZWNvbmRQb3ciOjIuNDc1ODgwMDc4NTcwNzYwNWUrMjcsInRoaXJkUG93IjoxLjg4ODk0NjU5MzE0Nzg1OGUrMjIsImZvdXJ0aFBvdyI6OTIyMzM3MjAzNjg1NDc3NjAwMCwiZmlmdGhQb3ciOjU2Mjk0OTk1MzQyMTMxMiwic2l4dGhQb3ciOjEwOTk1MTE2Mjc3NzYsInNldmVudGhQb3ciOjE3MTc5ODY5MTg0LCJlaWdodFBvdyI6MjY4NDM1NDU2LCJyZXNldHMiOjE2LCJ0aWNrRGVjcmVhc2UiOjAuODQsInRvdGFsbW9uZXkiOm51bGwsImludGVydmFsIjpudWxsfQ==

**Comment by IvarK** [comment]
You have reached the point where the numbers are bigger than the code can handle. The code can handle only up to 1e308 or so.

**Comment by wetfart99** [comment]
Thank you.
